version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-cont
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
      - ./mosquitto/certs:/mosquitto/certs:rw

    command: /bin/sh -c "mosquitto -c /mosquitto/config/mosquitto.conf"
   
  curl:
    image: alpine:latest
    container_name: curl-container
    volumes:
      - ./mosquitto/certs:/certs
      - ./curl:/entry_script
    entrypoint: >
      /bin/sh -c "
      apk update &&
      apk add openssl mosquitto-clients &&
      sh /entry_script/initialize_topics.sh
      "
   
volumes:
   config:
   data:
   log:
   certs:
   
networks:
   default:
      name: mosquitto-net
