version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/certs:/mosquitto/certs
    entrypoint: /bin/sh -c "/mosquitto/config/initialize_topics.sh && /docker-entrypoint.sh mosquitto"
